import Head from 'next/head'
import Layout from "../sections/Layout";

export default function Home() {
    return (
        <>
            <Layout>
                <Head>
                    <title>Hello</title>
                    <meta name="description" content="Generated by create next app"/>
                    <meta name="viewport" content="width=device-width, initial-scale=1"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>
                <main className="bg-amber-700 accent-red-50">
                    Hello world
                </main>
            </Layout>
        </>
    )
}
